#!/usr/bin/env python3
"""fsrs.py - spaced-repetition engine for a teaching classroom.

A dependency-free implementation of FSRS-5 (the Free Spaced Repetition
Scheduler, the algorithm Anki uses by default), adapted so the scheduled
*items* are TOPICS / SUB-CONCEPTS taught by lessons, not flashcards.

Each sub-concept carries three numbers FSRS tracks:
  - difficulty (D, 1..10)  : how intrinsically hard it is for this learner
  - stability  (S, days)   : days until predicted recall decays to ~90%
  - last_review (date)      : when it was last practised
From those we compute retrievability R (predicted recall right now) and the
next due date so that R will have decayed to the target retention.

Grades follow the FSRS 1..4 scale:
  1 = Again   (couldn't do it)
  2 = Hard    (got it with hints / gaps)
  3 = Good    (solid, minor slips)
  4 = Easy    (effortless)

State lives in a JSON file (default .claude/fsrs-state.json). PROGRESS.md is a
human-readable rendering regenerated by `render`.

Commands (run from the classroom root):
  init                                   create an empty state file
  add    --slug S --name N --lesson K [--date D]
                                         register a newly-taught sub-concept
  review --slug S --grade G [--date D]   record a graded review, reschedule
  due    [--date D] [--json]             list what is due (drives teach-init)
  render                                 (re)write PROGRESS.md from state
  list   [--json]                        dump every item
  optimize                               refit weights to your own review log
  selftest                               run a built-in sanity check

This file is meant to be readable and hackable: the FSRS weights and policy
constants are right below. Performance is irrelevant here (a few dozen float
ops a couple of times per session), so clarity wins.
"""

import argparse
import datetime as dt
import json
import math
import os
import sys

# --- FSRS-5 default parameters (w0..w18) -----------------------------------
# Trained on flashcard logs; a sensible default that yields the expanding
# intervals we want (≈1d → 3d → 1wk → 2wk → retire). Re-tune later if desired.
DEFAULT_W = [
    0.40255, 1.18385, 3.173, 15.69105, 7.1949, 0.5345, 1.4604, 0.0046,
    1.54575, 0.1192, 1.01925, 1.9395, 0.11, 0.29605, 2.2698, 0.2315,
    2.9898, 0.51655, 0.6621,
]

# Forgetting curve: R(t,S) = (1 + FACTOR * t / S) ** DECAY
DECAY = -0.5
FACTOR = 19.0 / 81.0           # = 0.9 ** (1 / DECAY) - 1
S_MIN = 0.01                   # floor on stability

# --- policy constants (safe to tune) ---------------------------------------
REQUEST_RETENTION = 0.90       # schedule so recall is ~90% at the due date
RETIRE_INTERVAL = 21           # interval >= this (days) => "consolidated"; your
                               # "after 3 weeks, stop" rule. Still fair game in exams.

# `optimize` refuses to run under this many observed reviews: refitting 19
# weights to a handful of data points just overfits noise.
MIN_REVIEWS_TO_OPTIMIZE = 50

DEFAULT_STATE = os.path.join(".claude", "fsrs-state.json")
DEFAULT_PROGRESS = "PROGRESS.md"


# --- small helpers ----------------------------------------------------------
def clamp(x, lo, hi):
    return max(lo, min(hi, x))


def today_date():
    return dt.date.today()


def parse_date(s):
    return dt.date.fromisoformat(s) if s else today_date()


# --- FSRS core math ---------------------------------------------------------
def retrievability(elapsed_days, stability):
    if stability <= 0:
        return 0.0
    return (1.0 + FACTOR * elapsed_days / stability) ** DECAY


def interval_for_retention(stability, retention=REQUEST_RETENTION):
    # invert the forgetting curve: days until R == retention
    return (stability / FACTOR) * (retention ** (1.0 / DECAY) - 1.0)


def init_stability(w, grade):
    return max(w[grade - 1], S_MIN)


def init_difficulty(w, grade):
    d = w[4] - math.exp(w[5] * (grade - 1)) + 1.0
    return clamp(d, 1.0, 10.0)


def next_difficulty(w, d, grade):
    delta = -w[6] * (grade - 3)
    d_new = d + delta * (10.0 - d) / 9.0           # linear damping
    target = init_difficulty(w, 4)                 # revert toward "Easy" baseline
    d_rev = w[7] * target + (1.0 - w[7]) * d_new   # mean reversion
    return clamp(d_rev, 1.0, 10.0)


def next_stability_recall(w, d, s, r, grade):
    hard_penalty = w[15] if grade == 2 else 1.0
    easy_bonus = w[16] if grade == 4 else 1.0
    growth = (
        math.exp(w[8])
        * (11.0 - d)
        * (s ** -w[9])
        * (math.exp(w[10] * (1.0 - r)) - 1.0)
        * hard_penalty
        * easy_bonus
    )
    return s * (1.0 + growth)


def next_stability_forget(w, d, s, r):
    s_forget = (
        w[11]
        * (d ** -w[12])
        * (((s + 1.0) ** w[13]) - 1.0)
        * math.exp(w[14] * (1.0 - r))
    )
    # a lapse should not make a topic more stable than before
    return min(s_forget, s)


# --- state I/O --------------------------------------------------------------
def empty_state():
    return {
        "version": 1,
        "request_retention": REQUEST_RETENTION,
        "retire_interval_days": RETIRE_INTERVAL,
        "weights": DEFAULT_W,
        "items": {},
    }


def load_state(path):
    if not os.path.exists(path):
        return empty_state()
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_state(state, path):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, ensure_ascii=False)
        f.write("\n")


# --- operations -------------------------------------------------------------
def cmd_init(args):
    if os.path.exists(args.state) and not args.force:
        print(f"State already exists at {args.state} (use --force to overwrite).")
        return
    save_state(empty_state(), args.state)
    print(f"Initialised empty FSRS state at {args.state}")


def cmd_add(args):
    state = load_state(args.state)
    items = state["items"]
    if args.slug in items and not args.force:
        print(f"'{args.slug}' already exists (use --force to overwrite).")
        return
    items[args.slug] = {
        "slug": args.slug,
        "name": args.name or args.slug,
        "lesson": args.lesson,
        "difficulty": None,
        "stability": None,
        "last_review": None,
        "due": None,
        "reps": 0,
        "lapses": 0,
        "status": "new",          # new -> active -> consolidated
        "history": [],
    }
    save_state(state, args.state)
    print(f"Added sub-concept '{args.slug}' (lesson {args.lesson}) as NEW.")


def cmd_review(args):
    state = load_state(args.state)
    w = state.get("weights", DEFAULT_W)
    rr = state.get("request_retention", REQUEST_RETENTION)
    retire = state.get("retire_interval_days", RETIRE_INTERVAL)
    items = state["items"]
    if args.slug not in items:
        print(f"Unknown sub-concept '{args.slug}'. Add it first.", file=sys.stderr)
        sys.exit(1)
    g = int(args.grade)
    if g not in (1, 2, 3, 4):
        print("grade must be 1..4", file=sys.stderr)
        sys.exit(1)
    today = parse_date(args.date)
    it = items[args.slug]

    if it["stability"] is None or it["last_review"] is None:
        # first practice: initial S/D from the grade
        s = init_stability(w, g)
        d = init_difficulty(w, g)
        r_used = None
    else:
        last = dt.date.fromisoformat(it["last_review"])
        elapsed = max(0, (today - last).days)
        r_used = retrievability(elapsed, it["stability"])
        d = next_difficulty(w, it["difficulty"], g)
        if g == 1:
            s = next_stability_forget(w, it["difficulty"], it["stability"], r_used)
            it["lapses"] += 1
        else:
            s = next_stability_recall(w, it["difficulty"], it["stability"], r_used, g)
    s = max(s, S_MIN)

    interval = interval_for_retention(s, rr)
    interval_days = max(1, round(interval))
    due = today + dt.timedelta(days=interval_days)
    status = "consolidated" if interval_days >= retire else "active"

    it["difficulty"] = round(d, 4)
    it["stability"] = round(s, 4)
    it["last_review"] = today.isoformat()
    it["due"] = due.isoformat()
    it["reps"] += 1
    it["status"] = status
    it["history"].append({
        "date": today.isoformat(),
        "grade": g,
        "r": round(r_used, 4) if r_used is not None else None,
        "interval": interval_days,
        "stability": round(s, 4),
        "difficulty": round(d, 4),
    })
    save_state(state, args.state)
    tag = " (CONSOLIDATED - retired from active review)" if status == "consolidated" else ""
    print(f"{args.slug}: grade {g} -> S={s:.2f} D={d:.2f}; next review in "
          f"{interval_days}d on {due.isoformat()}{tag}")


def _due_buckets(state, today):
    """Return (overdue, new) lists. overdue sorted by retrievability asc."""
    overdue, new = [], []
    for it in state["items"].values():
        if it["status"] == "consolidated":
            continue
        if it["status"] == "new" or it["due"] is None:
            new.append(it)
            continue
        due = dt.date.fromisoformat(it["due"])
        if due <= today:
            last = dt.date.fromisoformat(it["last_review"])
            elapsed = max(0, (today - last).days)
            r = retrievability(elapsed, it["stability"])
            overdue.append((r, (today - due).days, it))
    overdue.sort(key=lambda x: x[0])  # lowest recall first = most urgent
    return overdue, new


def cmd_due(args):
    state = load_state(args.state)
    today = parse_date(args.date)
    overdue, new = _due_buckets(state, today)

    if args.json:
        # `low_confidence` is an ADDED field (reps <= 1 => the prediction rests
        # on barely any evidence). Existing keys are kept for back-compat.
        print(json.dumps({
            "date": today.isoformat(),
            "due": [{"slug": it["slug"], "name": it["name"], "lesson": it["lesson"],
                     "r": round(r, 4), "overdue_days": od,
                     "reps": it["reps"], "low_confidence": it["reps"] <= 1}
                    for (r, od, it) in overdue],
            "new": [{"slug": it["slug"], "name": it["name"], "lesson": it["lesson"]}
                    for it in new],
        }, ensure_ascii=False, indent=2))
        return

    if not overdue and not new:
        print(f"Nothing due as of {today.isoformat()}. All caught up.")
        return
    if overdue:
        print(f"DUE FOR REVIEW ({len(overdue)}), most urgent first:")
        print("  (R = predicted recall, an FSRS estimate not a measurement; "
              "'~' marks low-confidence estimates from <=1 rep)")
        for (r, od, it) in overdue:
            od_txt = "today" if od == 0 else f"{od}d overdue"
            # A 1-rep estimate is barely earned; flag it so it reads as a guess.
            est = "~" if it["reps"] <= 1 else " "
            print(f"  - {it['slug']:32s} R{est}{r:0.2f}  L{it['lesson']}  ({od_txt})  [{it['name']}]")
    if new:
        print(f"NEW, not yet practised ({len(new)}):")
        for it in new:
            print(f"  - {it['slug']:32s} L{it['lesson']}  [{it['name']}]")


def cmd_list(args):
    state = load_state(args.state)
    if args.json:
        print(json.dumps(state, ensure_ascii=False, indent=2))
        return
    items = sorted(state["items"].values(), key=lambda it: (it["lesson"], it["slug"]))
    for it in items:
        print(f"L{it['lesson']:<3} {it['slug']:32s} {it['status']:12s} "
              f"D={it['difficulty']} S={it['stability']} due={it['due']} "
              f"reps={it['reps']} lapses={it['lapses']}")


def cmd_render(args):
    state = load_state(args.state)
    today = today_date()
    overdue, new = _due_buckets(state, today)
    items = sorted(state["items"].values(), key=lambda it: (it["lesson"], it["slug"]))
    n = len(items)
    n_active = sum(1 for it in items if it["status"] == "active")
    n_cons = sum(1 for it in items if it["status"] == "consolidated")
    n_new = sum(1 for it in items if it["status"] == "new")

    lines = []
    lines.append("# Progress")
    lines.append("")
    lines.append(f"_Regenerated by `fsrs.py render` on {today.isoformat()}._")
    lines.append("")
    lines.append(f"- Sub-concepts tracked: **{n}** "
                 f"({n_active} active, {n_cons} consolidated, {n_new} new)")
    lines.append(f"- Due for review today: **{len(overdue)}**")
    lines.append(f"- Awaiting first practice: **{len(new)}**")
    lines.append("")
    if overdue:
        lines.append("## Due now (most urgent first)")
        lines.append("")
        lines.append("_Predicted recall is an FSRS prediction, not a measurement. "
                     "Rows marked ~ (est.) rest on ≤1 rep, so treat them as a "
                     "guess rather than an earned estimate._")
        lines.append("")
        lines.append("| Sub-concept | Lesson | Predicted recall | Overdue |")
        lines.append("|---|---|---|---|")
        for (r, od, it) in overdue:
            od_txt = "today" if od == 0 else f"{od}d"
            # Flag low-rep predictions as uncertain.
            r_txt = f"~{r:0.2f} (est.)" if it["reps"] <= 1 else f"{r:0.2f}"
            lines.append(f"| {it['slug']} | L{it['lesson']} | {r_txt} | {od_txt} |")
        lines.append("")
    lines.append("## All sub-concepts")
    lines.append("")
    lines.append("| Sub-concept | Lesson | Status | D | S (days) | Last | Due | Reps | Lapses |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for it in items:
        lines.append(
            f"| {it['slug']} | L{it['lesson']} | {it['status']} | "
            f"{it['difficulty'] if it['difficulty'] is not None else '-'} | "
            f"{it['stability'] if it['stability'] is not None else '-'} | "
            f"{it['last_review'] or '-'} | {it['due'] or '-'} | "
            f"{it['reps']} | {it['lapses']} |"
        )
    lines.append("")
    with open(args.progress, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {args.progress} ({n} sub-concepts).")


# --- optimize: recalibrate weights to the learner's own review log ----------
#
# The default weights were trained on flashcard logs (see DEFAULT_W). The
# per-item `history` we already log is enough to ask: did this learner's actual
# recall match what the model predicted? If not, nudge the weights until the
# predicted retrievability-at-review lines up better with what really happened.
#
# We can't trust the `r` stored in each history entry (it was computed under the
# OLD weights), so for a candidate weight vector we REPLAY each item's history
# from scratch — init_stability/init_difficulty, then next_stability_* and
# next_difficulty exactly as cmd_review does — to get *this* candidate's
# predicted r at every review. We then score those predictions against the
# observed outcome (grade >= 3 => recalled) with binary log-loss.
#
# The search is a dependency-free coarse coordinate descent: try bumping each
# weight up/down by shrinking steps, keep any change that lowers log-loss.
# Slow and simple is fine here (a few dozen items, run rarely).

EPS = 1e-9  # keep log() away from 0/1


def _collect_observations(state):
    """Flatten every item's history into replayable per-item review sequences.

    Returns a list of items, each a list of (grade, recalled) review tuples in
    chronological order, but ONLY including reviews where a prediction is
    meaningful (r was not null, i.e. not the first practice). The first practice
    has no predicted recall to score, but we still need to replay it to seed S/D,
    so we keep the whole sequence and mark which steps are scorable.

    Each replayable item is a list of dicts:
      {"grade": g, "recalled": 0/1 or None, "scorable": bool}
    """
    items = []
    for it in state["items"].values():
        hist = it.get("history") or []
        if not hist:
            continue
        seq = []
        for h in hist:
            g = int(h["grade"])
            scorable = h.get("r") is not None  # first practice has r == null
            recalled = (1 if g >= 3 else 0) if scorable else None
            seq.append({"grade": g, "recalled": recalled, "scorable": scorable})
        items.append(seq)
    return items


def _replay_predictions(w, items):
    """Replay every item under weights `w`, yielding (predicted_r, recalled).

    Mirrors cmd_review's math: first practice seeds S/D from the grade (no
    prediction to score); each later review computes the predicted r BEFORE the
    grade is known, then updates S/D. We don't have stored elapsed days here, so
    we use the model's own scheduled interval (interval_for_retention at the
    request retention) as the elapsed time — i.e. "assume the review happened on
    its due date". That's the same simplifying assumption the schedule makes, and
    it keeps the replay self-contained.
    """
    preds = []  # list of (predicted_r, observed_recalled)
    for seq in items:
        s = d = None
        for step in seq:
            g = step["grade"]
            if s is None:
                # first practice: seed S/D, nothing to predict yet
                s = max(init_stability(w, g), S_MIN)
                d = init_difficulty(w, g)
                continue
            # predict recall at the (assumed) due date, then update like review
            elapsed = max(1, round(interval_for_retention(s)))
            r = retrievability(elapsed, s)
            if step["scorable"]:
                preds.append((r, step["recalled"]))
            d = next_difficulty(w, d, g)
            if g == 1:
                s = next_stability_forget(w, d, s, r)
            else:
                s = next_stability_recall(w, d, s, r, g)
            s = max(s, S_MIN)
    return preds


def _log_loss(preds):
    """Mean binary log-loss over (predicted_r, recalled) pairs."""
    if not preds:
        return float("inf")
    total = 0.0
    for r, y in preds:
        p = clamp(r, EPS, 1.0 - EPS)
        total += -(y * math.log(p) + (1 - y) * math.log(1.0 - p))
    return total / len(preds)


def _accuracy(preds, threshold=0.5):
    """Fraction where predicted recall (>= threshold) matched the outcome."""
    if not preds:
        return 0.0
    correct = sum(1 for r, y in preds if (1 if r >= threshold else 0) == y)
    return correct / len(preds)


def _coordinate_descent(w0, items):
    """Coarse local search over the 19 weights. Returns the best weight vector.

    For each shrinking step size, sweep every weight, trying +/- step; keep a
    move whenever it strictly lowers log-loss. Repeat until a full sweep at the
    smallest step makes no improvement. Weights are kept non-negative (every
    DEFAULT_W entry is >= 0 and the math assumes it).
    """
    w = list(w0)
    best = _log_loss(_replay_predictions(w, items))
    for step in (1.0, 0.3, 0.1, 0.03, 0.01):
        improved = True
        while improved:
            improved = False
            for i in range(len(w)):
                for delta in (step, -step):
                    cand = list(w)
                    cand[i] = max(0.0, cand[i] + delta)
                    if cand[i] == w[i]:
                        continue
                    loss = _log_loss(_replay_predictions(cand, items))
                    if loss < best - 1e-12:
                        w, best = cand, loss
                        improved = True
    return w


def cmd_optimize(args):
    state = load_state(args.state)
    w_old = state.get("weights", DEFAULT_W)

    items = _collect_observations(state)
    n_reviews = sum(1 for seq in items for step in seq if step["scorable"])

    if n_reviews < MIN_REVIEWS_TO_OPTIMIZE:
        print(f"Only {n_reviews} scorable review(s) in history; need at least "
              f"{MIN_REVIEWS_TO_OPTIMIZE} to optimize reliably. Keeping current "
              f"weights (refitting 19 weights to so few points just overfits noise).")
        return

    preds_old = _replay_predictions(w_old, items)
    loss_old = _log_loss(preds_old)
    acc_old = _accuracy(preds_old)
    print(f"Fitting weights to {n_reviews} observed reviews across "
          f"{len(items)} item(s)...")
    print(f"  before: log-loss={loss_old:.4f}  accuracy={acc_old:.3f}")

    w_new = _coordinate_descent(w_old, items)
    preds_new = _replay_predictions(w_new, items)
    loss_new = _log_loss(preds_new)
    acc_new = _accuracy(preds_new)
    print(f"  after:  log-loss={loss_new:.4f}  accuracy={acc_new:.3f}")

    # Only commit the fit if it actually improves the (training) log-loss.
    if loss_new < loss_old - 1e-9:
        state["weights"] = [round(x, 6) for x in w_new]
        save_state(state, args.state)
        print(f"Improved log-loss by {loss_old - loss_new:.4f}; wrote new "
              f"weights to {args.state}.")
    else:
        print("No improvement found; keeping existing weights unchanged.")


def cmd_selftest(args):
    """Sanity check: a 'Good' track should expand; an 'Again' should shrink."""
    w = DEFAULT_W
    print("DECAY", DECAY, "FACTOR", round(FACTOR, 6))
    print("interval at S=10, r=0.9 ->", round(interval_for_retention(10, 0.9), 4),
          "(should equal S)")
    # simulate repeated Good reviews
    d = init_difficulty(w, 3)
    s = init_stability(w, 3)
    print(f"\nGood/Good/Good track (D0={d:.2f}, S0={s:.2f}):")
    last_iv = max(1, round(interval_for_retention(s)))
    print(f"  rep1 -> interval {last_iv}d")
    for rep in range(2, 6):
        r = retrievability(last_iv, s)
        s = max(next_stability_recall(w, d, s, r, 3), S_MIN)
        d = next_difficulty(w, d, 3)
        iv = max(1, round(interval_for_retention(s)))
        print(f"  rep{rep} -> R@due={r:.2f}  S={s:.2f}  D={d:.2f}  interval {iv}d")
        assert iv >= last_iv, "intervals should not shrink on consistent Good"
        last_iv = iv
    # a lapse should shrink stability
    r = retrievability(last_iv, s)
    s_lapse = next_stability_forget(w, d, s, r)
    print(f"\n  lapse (Again) from S={s:.2f} -> S={s_lapse:.2f}")
    assert s_lapse < s, "a lapse should reduce stability"
    print("\nselftest OK")


def build_parser():
    p = argparse.ArgumentParser(description="FSRS spaced-repetition engine for a classroom.")
    p.add_argument("--state", default=DEFAULT_STATE, help="path to state JSON")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("init", help="create an empty state file")
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("add", help="register a newly-taught sub-concept")
    s.add_argument("--slug", required=True)
    s.add_argument("--name", default=None)
    s.add_argument("--lesson", type=int, required=True)
    s.add_argument("--date", default=None)
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_add)

    s = sub.add_parser("review", help="record a graded review and reschedule")
    s.add_argument("--slug", required=True)
    s.add_argument("--grade", required=True)
    s.add_argument("--date", default=None)
    s.set_defaults(func=cmd_review)

    s = sub.add_parser("due", help="list sub-concepts due for review")
    s.add_argument("--date", default=None)
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_due)

    s = sub.add_parser("list", help="dump every item")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_list)

    s = sub.add_parser("render", help="regenerate PROGRESS.md")
    s.add_argument("--progress", default=DEFAULT_PROGRESS)
    s.set_defaults(func=cmd_render)

    s = sub.add_parser("optimize", help="refit weights to your own review log")
    s.set_defaults(func=cmd_optimize)

    s = sub.add_parser("selftest", help="run a built-in sanity check")
    s.set_defaults(func=cmd_selftest)

    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
